language: java
sudo: false

# Build all the code on each JDK, but only build Javadoc on JDK8:
matrix:
  include:
    - env: BUILD_DOCS=true
      jdk: oraclejdk8
    - jdk: oraclejdk7
    - jdk: openjdk7
    - jdk: openjdk6

script:
 - ant all
 - if [ "$BUILD_DOCS" == "true" ]; then
      ant javadoc;
      git config --global user.email "chodapp3@gatech.edu"
      git config --global user.name "Chris Hodapp"
      git add docs;
      git commit -m "Automatic Travis commit from build ${TRAVIS_BUILD_NUMBER}";
      git push;
   fi

# TODO:
    # Add in JUnit tests.
    # Are any code coverage tools good to have here for Javadoc & JUnit?
    # Get Javadoc warnings into some sort of page?
    # I should put the git email & name in an environment variable